name: Run unittests.
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        #go: ['1.16.5', '1.17.0-beta1', '1.17.0-rc1']
        go: ['>=1.22.4']

    env:
        GOPRIVATE: github.com/iredmail/vmail,github.com/iredmail/gosible,github.com/iredmail/ldappool
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - run: make testv

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          #version: v2.5.2
          version: latest
          args: --print-issued-lines -c $GITHUB_WORKSPACE/.golangci.yml
          #only-new-issues: false
          skip-go-installation: true
          skip-pkg-cache: false
          skip-build-cache: false

    #- name: Gosec
    #  uses: securego/gosec@master
    #  with:
    #    # we let the report trigger content trigger a failure using the GitHub Security features.
    #    # G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    #    #args: '-exclude G304 -no-fail -fmt sarif -out results.sarif ./...'
    #    args: '-no-fail -nosec -quiet -exclude G101,G304,G402,G404 ./internal/... ./cmd/...'
